version: "3.9"

services:
  zeyrek:
    build:
      context: .
      dockerfile: Dockerfile
    image: tr-lemmatizer-zeyrek:1.0.0
    container_name: zeyrek
    ports: ["8077:8077"]
    restart: unless-stopped
    environment:
      ZEYREK_CACHE_DIR: /srv/.zeyrek_cache
    volumes:
      - zeyrek-cache:/srv/.zeyrek_cache
    healthcheck:
      test:
        - "CMD-SHELL"
        - |
          python - <<'PY'
          import urllib.request,sys
          try: urllib.request.urlopen('http://localhost:8077/health',timeout=3); sys.exit(0)
          except Exception: sys.exit(1)
          PY
      interval: 60s
      timeout: 8s
      retries: 10
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          memory: 256M

volumes:
  zeyrek-cache:
