version: "3.9"

services:
  zeyrek:
    build:
      context: .
      dockerfile: Dockerfile
    image: tr-lemmatizer-zeyrek:1.0.0
    container_name: zeyrek
    expose: ["8077"]
    restart: unless-stopped
    healthcheck:
      test:
        - "CMD-SHELL"
        - |
          python - <<'PY'
          import urllib.request,sys
          try: urllib.request.urlopen('http://localhost:8077/health',timeout=2); sys.exit(0)
          except Exception: sys.exit(1)
          PY
      interval: 120s
      timeout: 5s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          memory: 256M
